---
- hosts: localhost
  connection: local

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "awskey"
        instance_type: t2.micro
        security_group: default
        region: us-east-1
        aws_access_key: "{{ ec2_access_key }}"  # From vault as defined
        aws_secret_key: "{{ ec2_secret_key }}"  # From vault as defined      
        network_interfaces:
          - assign_public_ip: true
        image_id: "{{ item.image }}"
      loop:
        - { image: "ami-084568db4383264d4", name: "manage-node-1" } # Update AMI ID according 
        - { image: "ami-084568db4383264d4", name: "manage-node-2" } # to your account
        - { image: "ami-00a929b66ed6e0de6", name: "manage-node-3" }
